### ISSUE TITLE
 Create an ophyd device for Applet2 undulator 

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/dodal#724]
I17 will be using the same type of ID as I10, I21 and I06. This issue is to create an ophyd_async device to control this type of ID.
This type of ID has 4 extra degrees of freedom beside the gap, each bank of magnet can move independently to each other. To produce different polarisation as well as energy.

User expected to be able to set energy and polarisation states: PC, NC, LH, LV and LA. With LA there will also be a polarisation angle associated with this state.
These polarisation states are achieved by moving the ID motors into its correct position using a lookup table, each polarisation has their own look up table, therefore changing polarisation is effectively changing look up table.
Also worth noting that, motors movement should be together. E.g. set point is put to epics pv but nothing should move until all axis is set and they should be move together, 

## Acceptance Criteria
Create an applet2 id device that can move all the id's motors. similar to [undulator](src/dodal/devices/undulator.py)
Must connect all required PV.
Passes tests.

## Ref:
/dls_sw/work/R3.14.12.7/ioc/BL10I/BL10I-CS-GATE-01/5064/P/gateway.pvlist
/dls_sw/work/R3.14.12.7/ioc/BL21I/BL21I-CS-GATE-01/5064/P/gateway.pvlist

/dls_sw/work/R3.14.12.7/support/insertionDevice/db/IDGapSoftMotor.template
/dls_sw/work/R3.14.12.7/support/insertionDevice/db/IDPhaseSoftMotor.template
/dls_sw/work/R3.14.12.7/support/insertionDevice/db/IDGapVelocityControl.template

GDA implementation:
/dc/dls_sw/i10/software/gda/workspace_git/gda-diamond.git/configurations/i10-shared/scripts/calibrations/mode_polarisation_energy_instances.py
/calibrations/energy_polarisation_class.py
lookup tables:
/i10-shared/lookupTables/IDEnergy2GapCalibrations.csv
/i10-shared/lookupTables/IDEnergy2PhaseCalibrations.csv

**Comment by Relm-Arrowny** [comment]
@DominicOram @stan-dot I saw the id issue on i18 and wondering if you two have any tips and comment on this? Especially, I want to make sure no such device already exist and any advice on best/standard way to implement the extra lookup table/ x-ray polarisation would be much appreciated.

**Comment by stan-dot** [comment]
@Relm-Arrowny  for me this link is broken: 
``` Create an applet2 id device that can move all the id's motors. similar to [undulator](https://github.com/DiamondLightSource/dodal/issues/src/dodal/devices/undulator.py)



which i18 id issue?

**Comment by Relm-Arrowny** [comment]
[this](https://github.com/DiamondLightSource/dodal/issues/706) Saw you two discussing undulator and thought I ask :p.

**Comment by DominicOram** [comment]
You may be able to re-use https://github.com/DiamondLightSource/dodal/pull/721 but it depends on the exact logic. Is it that:
* Changing the energy still only changes the gap demand PV
* The lookup table used for this demand is different and will change based on the polarisations
* Changing the polarisations changes this lookup table and changes some of the phase demand positions too

Or is it that:
* Changing the energy will change the gap demand and phase demand PVs
* How these change are based on lookup tables
* These tables are set based on polarisation

If it's the first I think you can reuse the existing undulator quite a bit, if it's the second I would write an ABC that they share so that we can use them interchangeably but otherwise have two separate devices.
